id: I504749BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:18:22+00:00'
last_modified: '2022-06-08T06:21:40.868928+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17446
  title: མཁས་པ་འཇུག་པའི་སྒོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E4D4:
      image_group_id: I1KG18243
      title: ''
      total_pages: 166
      order: 1
      base_file: E4D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
