id: P006661
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17446
  title: མཁས་པ་འཇུག་པའི་སྒོ།
  author: ''
  volumes:
    55e9e80c9a3545c987c7006e2425b3cb:
      image_group_id: I1KG18243
      title: ''
      volume_number: 1
      total_pages: 166
